export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAILURE = "APPLY_JOB_FAILURE";
export const APPLY_JOB_REQUEST =  "APPLY_JOB_REQUEST"
export const JOB_SUCCESS = "JOB_SUCCESS";//for reducer
export const JOB_FAILURE = "JOB_FAILURE";//for reducer

export const CANCEL_JOB_SUCCESS = "CANCEL_JOB_SUCCESS";
export const CANCEL_JOB_FAILURE = "CANCEL_JOB_FAILURE";
export const CANCEL_SUCCESS = "CANCEL_SUCCESS";
export const CANCEL_FAILURE = "CANCEL_FAILURE";

export const SAVE_JOB_SUCCESS = "SAVE_JOB_SUCCESS";
export const SAVE_JOB_FAILURE = "SAVE_JOB_FAILURE";

export const UNSAVE_JOB_SUCCESS = "UNSAVE_JOB_SUCCESS";
export const UNSAVE_JOB_FAILURE = "UNSAVE_JOB_FAILURE";

export const SAVE_SUCCESS = "SAVE_SUCCESS";
export const SAVE_FAILURE = "SAVE_FAILURE";

export const APPLIED_JOB_SUCCESS = "APPLIED_JOB_SUCCESS";
export const APPLIED_JOB_FAILURE = "APPLIED_JOB_FAILURE";
export const APPLIED_JOB_REQUEST = "APPLIED_JOB_REQUEST";
export const APPLIED_SUCCESS = "APPLIED_SUCCESS";
export const APPLIED_FAILURE = "APPLIED_FAILURE";




