export const DELETE_JOB_ALERT_SUCCESS = "DELETE_JOB_ALERT_SUCCESS";
export const DELETE_JOB_ALERT_FAILURE = "DELETE_JOB_ALERT_FAILURE";
//for Reducer
export const DELETE_JOB_ALERT_SUCCESS_RESPONSE = "DELETE_JOB_ALERT_SUCCESS_RESPONSE";
export const DELETE_JOB_ALERT_FAILURE_RESPONSE = "DELETE_JOB_ALERT_FAILURE_RESPONSE";