export const EDIT_JOB_ALERT_SUCCESS = "EDIT_JOB_ALERT_SUCCESS";
export const EDIT_JOB_ALERT_FAILURE = "EDIT_JOB_ALERT_FAILURE";

//for Reducer
export const EDIT_JOB_ALERT_SUCCESS_RESPONSE = "EDIT_JOB_ALERT_SUCCESS_RESPONSE";
export const EDIT_JOB_ALERT_FAILURE_RESPONSE = "EDIT_JOB_ALERT_FAILURE_RESPONSE";