// reducer

export const EDIT_CONSULTANT_REQUEST_REDUCER = "EDIT_CONSULTANT_REQUEST";
export const EDIT_CONSULTANT_SUCCESS_REDUCER = "EDIT_CONSULTANT_SUCCESS";
export const EDIT_CONSULTANT_FAILURE_REDUCER = "EDIT_CONSULTANT_FAILURE";
