export const FETCH_JOB_FORM_DATA = "FETCH_JOB_FORM_DATA";
export const SET_JOB_FORM_DATA = "SET_JOB_FORM_DATA";
export const SET_JOB_FORM_SUCCESS = "SET_JOB_FORM_SUCCESS";
export const SUBMIT_JOB_FORM_DATA = "SUBMIT_FORM_DATA";
export const JOB_EDIT_SUCCESS = "JOB_EDIT_SUCCESS";
export const JOB_EDIT_FAILURE = "JOB_EDIT_FAILURE";

