export const FETCH_FORM_DATA = "FETCH_FORM_DATA";
export const SET_FORM_DATA = "SET_FORM_DATA";
export const SET_FORM_SUCCESS = "SET_FORM_SUCCESS";
export const SUBMIT_FORM_DATA = "SUBMIT_FORM_DATA";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAILURE = "PROFILE_EDIT_FAILURE";

