export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_ERROR = "FACEBOOK_LOGIN_ERROR";
export const FACEBOOK_LOGIN_REDIRECT = "FACEBOOK_LOGIN_REDIRECT";
