export const FETCH_APPLIED_CONSULTANT_REQUEST =
  "FETCH_APPLIED_CONSULTANT_REQUEST";
export const FETCH_APPLIED_CONSULTANT_SUCCESS =
  "FETCH_APPLIED_CONSULTANT_SUCCESS";
export const FETCH_APPLIED_CONSULTANT_FAILURE =
  "FETCH_APPLIED_CONSULTANT_FAILURE";

export const REMOVE_APPLIED_CONSULTANT_REQUEST =
  "REMOVE_APPLIED_CONSULTANT_REQUEST";
export const REMOVE_APPLIED_CONSULTANT_SUCCESS =
  "REMOVE_APPLIED_CONSULTANT_SUCCESS";
export const REMOVE_APPLIED_CONSULTANT_FAILURE =
  "REMOVE_APPLIED_CONSULTANT_FAILURE";
