
export const FETCH_APPLIED_CONSULTANT_REQUEST = 'FETCH_APPLIED_CONSULTANT_REQUEST';
export const FETCH_APPLIED_CONSULTANT_SUCCESS = 'FETCH_APPLIED_CONSULTANT_SUCCESS';
export const FETCH_APPLIED_CONSULTANT_FAILURE = 'FETCH_APPLIED_CONSULTANT_FAILURE';
