export const GENERATE_SKILLS_SAVE_REQUEST = "GENERATE_SKILLS_SAVE_REQUEST";
export const GENERATE_SKILLS_SAVE_SUCCESS = "GENERATE_SKILLS_SAVE_SUCCESS";
export const GENERATE_SKILLS_SAVE_FAILURE = "GENERATE_SKILLS_SAVE_FAILURE";
export const GENERATE_SKILLS_SAVE_LOADING = "GENERATE_SKILLS_SAVE_LOADING";
