export const GENERATE_RESPONSE_SAVE_REQUEST = "GENERATE_RESPONSE_SAVE_REQUEST";
export const GENERATE_RESPONSE_SAVE_SUCCESS = "GENERATE_RESPONSE_SAVE_SUCCESS";
export const GENERATE_RESPONSE_SAVE_FAILURE = "GENERATE_RESPONSE_SAVE_FAILURE";
export const GENERATE_RESPONSE_SAVE_LOADING = "GENERATE_RESPONSE_SAVE_LOADING";
