export const POST_JOB_ALERT_SUCCESS = "POST_JOB_ALERT_SUCCESS";
export const POST_JOB_ALERT_FAILURE = "POST_JOB_ALERT_FAILURE";

// FOR REDUCER POST JOB ALERT TYPE
export const POST_JOB_ALERT_SUCCESS_RESPONSE = "POST_JOB_ALERT_SUCCESS_RESPONSE"
export const POST_JOB_ALERT_FAILURE_RESPONSE = "POST_JOB_ALERT_FAILURE_RESPONSE"
