// Recent Job on search
export const FETCH_RECENT_JOBS = "FETCH_RECENT_JOBS";
export const FETCH_RECENT_JOBS_SUCCESS = "FETCH_RECENT_JOBS_SUCCESS";
export const FETCH_RECENT_JOBS_FAILURE = "FETCH_RECENT_JOBS_SUCCESS";

// Delete Recent Job on search
export const DELETE_RECENT_JOBS = "DELETE_RECENT_JOBS";
export const DELETE_RECENT_JOBS_SUCCESS = "DELETE_RECENT_JOBS_SUCCESS";
export const DELETE_RECENT_JOBS_FAILURE = "DELETE_RECENT_JOBS_SUCCESS";
