export const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE";

// type of param recommand job
export const FETCH_RECOMMAND_JOBS = "FETCH_RECOMMAND_JOBS";
export const FETCH_RECOMMAND_JOBS_SUCCESS = "FETCH_RECOMMAND_JOBS_SUCCESS";
export const FETCH_RECOMMAND_JOBS_FAILURE = "FETCH_RECOMMAND_JOBS_FAILURE";
