
export const SAVED_JOB_SUCCESS = "SAVED_JOB_SUCCESS";
export const SAVED_JOB_FAILURE = "SAVED_JOB_FAILURE";
export const SAVED_JOB_REQUEST = "SAVED_JOB_REQUEST";
// export const SAVED_SUCCESS = "SAVED_SUCCESS";
// export const SAVED_FAILURE = "SAVED_FAILURE";