
export const ADD_SCHEDULE_CONSULTANT_REQUEST = 'ADD_SCHEDULE_CONSULTANT_REQUEST';
export const ADD_SCHEDULE_CONSULTANT_SUCCESS = 'ADD_SCHEDULE_CONSULTANT_SUCCESS';
export const ADD_SCHEDULE_CONSULTANT_FAILURE = 'ADD_SCHEDULE_CONSULTANT_FAILURE'

export const REJECT_SCHEDULE_CONSULTANT_REQUEST = 'REJECT_SCHEDULE_CONSULTANT_REQUEST';
export const REJECT_SCHEDULE_CONSULTANT_SUCCESS = 'REJECT_SCHEDULE_CONSULTANT_SUCCESS';
export const REJECT_SCHEDULE_CONSULTANT_FAILURE = 'REJECT_SCHEDULE_CONSULTANT_FAILURE';