export const ADD_SELECT_CONSULTANT_REQUEST = "ADD_SELECT_CONSULTANT_REQUEST";
export const ADD_SELECT_CONSULTANT_SUCCESS = "ADD_SELECT_CONSULTANT_SUCCESS";
export const ADD_SELECT_CONSULTANT_FAILURE = "ADD_SELECT_CONSULTANT_FAILURE";

export const FETCH_SELECTED_CONSULTANT_REQUEST =
  "FETCH_SELECTED_CONSULTANT_REQUEST";
export const FETCH_SELECTED_CONSULTANT_SUCCESS =
  "FETCH_SELECTED_CONSULTANT_SUCCESS";
export const FETCH_SELECTED_CONSULTANT_FAILURE =
  "FETCH_SELECTED_CONSULTANT_FAILURE";

export const REJECT_SELECT_CONSULTANT_REQUEST =
  "REJECT_SELECT_CONSULTANT_REQUEST";
export const REJECT_SELECT_CONSULTANT_SUCCESS =
  "REJECT_SELECT_CONSULTANT_SUCCESS";
export const REJECT_SELECT_CONSULTANT_FAILURE =
  "REJECT_SELECT_CONSULTANT_FAILURE";
