
export const ADD_SHORTLIST_REQUEST = 'ADD_SHORTLIST_REQUEST';
export const ADD_SHORTLIST_SUCCESS = 'ADD_SHORTLIST_SUCCESS';
export const ADD_SHORTLIST_FAILURE = 'ADD_SHORTLIST_FAILURE';

export const FETCH_SHORTLISTED_COSULTANT_REQUEST = 'FETCH_SHORTLISTED_COSULTANT_REQUEST';
export const FETCH_SHORTLISTED_SUCCESS = 'FETCH_SHORTLISTED_COSULTANT_SUCCESS';
export const FETCH_SHORTLISTED_COSULTANT = 'FETCH_SHORTLISTED_COSULTANT_FAILURE';