export const USER_NOTIFICATION_TYPE = "USER_NOTIFICATION_TYPE";
export const USER_NOTIFICATION_TYPE_SUCCESS = "USER_NOTIFICATION_TYPE_SUCCESS";
export const USER_NOTIFICATION_TYPE_FAILURE = "USER_NOTIFICATION_TYPE_FAILURE";
